version: 0.0
os: linux

files:
  - source: #source location of deployable
    destination: #destination location of deployable

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: centos
  AfterInstall:
    - location: scripts/change_permissions.sh
      timeout: 300
      runas: centos
  ApplicationStart:
    - location: scripts/start_server.sh
    - location: scripts/create_test_db.sh
      timeout: 300
      runas: centos
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: centos

