version: 2
jobs:
  build:
    branches:
      only:
        - master #Only building for master branch pushes
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Install packages
          command: |
            sudo apt-get update && sudo apt-get install wget zip unzip python-pip python-dev build-essential -y
            python --version
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Build Artifact
          command: |
            cd webapp/cloud-ninja
            pwd
            ls -al
            echo "Building the artifact with Maven"
            mvn clean install
            cd target
            ls -al
            cd ../../..
      - run:
          name: Zip Artifact
          command: |
            echo "Hello the current build number is ${CIRCLE_BUILD_NUM}"
            pwd
            echo "Listing current directory content"
            ls -al
            echo "Making the codedeploy_artifact directory"
            mkdir -p codedeploy_artifact
            echo "Changing directory to codedeploy_artifact"
            cd codedeploy_artifact
            echo "Copying all .sh files from ../infrastructure/aws/codedeploy directory to the codedeploy_artifact"
            cp ../infrastructure/aws/codedeploy/*.sh .
            echo "Copying all .yml files from ../ directory to the codedeploy_artifact"
            cp ../*.yml .
            echo "Copying the jar file from ../webapp/cloud-ninja/target/cloud-ninja-SNAPSHOT.jar to the codedeploy_artifact"
            cp ../webapp/cloud-ninja/target/cloud-ninja-SNAPSHOT.jar .
            echo "Copying the properties from /webapp/cloud-ninja/src/main/resources to the codedeploy_artifact"
            cp ../webapp/cloud-ninja/src/main/resources/*.properties .
            echo "Zipping all files in the codedeploy_artifact directory"
            zip -r cloud-ninja-webapp-${CIRCLE_BUILD_NUM}.zip .
            echo "Removing the files except for the zip file from the codedeploy_artifact directory"
            rm *.yml *.sh *.jar *.properties
            ls -al
            pwd
            echo "Changing directory to root"
            cd ..
            pwd
            ls -al
      - run:
          name: Upload Artifact to S3
          command: |
            echo "Uploading Artifact to S3 bucket ${CODE_DEPLOY_S3_BUCKET}"
            cd codedeploy_artifact
            aws s3 cp cloud-ninja-webapp-${CIRCLE_BUILD_NUM}.zip s3://${CODE_DEPLOY_S3_BUCKET}
            cd ..
      - run:
          name: Make CodeDeploy API call
          command: |
            echo "Calling CodeDeploy Agent to pick the artifact and deploy on EC2 instance"
            echo "Calling CodeDeploy Agent to pick the artifact and deploy on EC2 instance"
            pwd
            echo "Listing current directory content"
            ls -al
            aws deploy create-deployment --application-name "csye6225-webapp" --deployment-group-name "csye6225-webapp-deployment" --s3-location bucket=${s3bucket},bundleType=zip,key=cloud-ninja-webapp-${CIRCLE_BUILD_NUM}.zip
            echo "Listing current directory content"
            ls -al
